export const props = [
  {
    id: 14298,
    archivo: 'm9999019.005',
    aduana: 470,
    fechaRecibido: '2022-05-24T02:31:43.000Z',
    fechaProcesado: null,
    fechaRespuesta: null,
    status: 1,
    resultado: null,
    tipoArchivo: 1,
    idContacto: 94915,
    idCliente: 50805,
    idPrevalidador: 55,
    aduanaNombre:
      'AEROPUERTO INTERNACIONAL "LIC. BENITO JUAREZ", CD. DE MEXICO, D.F.              ',
    patenteIdPatenteAnterior: null,
    patenteIdRepresentanteLegal: null,
    patenteAsociado: null,
    patenteTipo: null,
    clienteId: 50805,
    clienteRazonSocial: 'GOMSA INTEGRADORA, S.A.P.I. DE C.V.',
    clientRfc: 'GIN140609RE5 ',
    contactoId: null,
    nombreContacto: null,
    apellidoContacto: null,
  },
  {
    id: 14299,
    archivo: 'm9999140.031',
    aduana: 470,
    fechaRecibido: '2022-05-24T05:15:39.000Z',
    fechaProcesado: null,
    fechaRespuesta: null,
    status: 1,
    resultado: null,
    tipoArchivo: 1,
    idContacto: 94915,
    idCliente: 50805,
    idPrevalidador: 55,
    aduanaNombre:
      'AEROPUERTO INTERNACIONAL "LIC. BENITO JUAREZ", CD. DE MEXICO, D.F.              ',
    patenteIdPatenteAnterior: null,
    patenteIdRepresentanteLegal: null,
    patenteAsociado: null,
    patenteTipo: null,
    clienteId: 50805,
    clienteRazonSocial: 'GOMSA INTEGRADORA, S.A.P.I. DE C.V.',
    clientRfc: 'GIN140609RE5 ',
    contactoId: null,
    nombreContacto: null,
    apellidoContacto: null,
  },
];
